### ISSUE TITLE
Custom message always sent to user

### ISSUE THREAD

**Issue by theit8514** [Nicologies/teamcity-slack#5]
I have Hedwig set up on my TeamCity server (just a minor note, the 1.0.4 release of hedwig.zip on the releases page has teamcity_plugin.xml which my server didn't recognize), and I've been testing it for sending custom messages. I currently have this line setup to send out release notifications:

`##teamcity[Hedwig Status='Succeeded' StatusType='Succeeded' MsgName0='Release Link' MsgValue0='http://s3/path/to/file.zip' Branch='master' Users='' Channels='release_notifications']`

I am always getting the message to my slackbot channel. I assume this is because I triggered the builds, but is it possible to force the message to only be sent to the channel?

**Comment by EbenZhang** [comment]
should be fixed in https://github.com/Nicologies/Hedwig/releases/tag/1.0.5

**Comment by EbenZhang** [comment]
fixed in https://github.com/Nicologies/Hedwig/releases/tag/1.0.6
